<#
.SYNOPSIS
    Get GLPI Session Token.
.DESCRIPTION
    This function getting session token generated by initSession.
.EXAMPLE
    PS C:\Users\Wojtek> Get-GlpiToolsSessionToken
    Running script like that, shows you the current session token.
.INPUTS
    None
.OUTPUTS
    String or null
.NOTES
    PSP 12/2018
#>

function Get-GlpiToolsSessionToken {
    [CmdletBinding()]
    param (
        
    )
    
    begin {


    }
    
    process {

        if($global:GlpiToolsSessionToken -eq $null){
			Set-GlpiToolsInitSession
		}
		else {
			$global:GlpiToolsSessionToken
		}
    }
    
    end {
		
    }
}